name: project-who-tf-dev
services:
  mariadb:
    image: mariadb:11.4.5
    environment:
      MARIADB_DATABASE: who_tf_dev
      MARIADB_USER: who_tf_dev
      MARIADB_PASSWORD: who_tf_dev
      MARIADB_ROOT_PASSWORD: who_tf_dev
    ports:
      - "8379:3306"
    volumes:
      - project-who-tf-dev-mariadb-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pwho_tf_dev" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: valkey/valkey:9.0-alpine3.22
    ports:
      - "8380:6379"
    volumes:
      - project-who-tf-dev-redis-data:/data
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: valkey-server --appendonly yes

volumes:
  project-who-tf-dev-mariadb-data:
    driver: local
  project-who-tf-dev-redis-data:
    driver: local
